New upstream release; fix lintian errors

diff --git a/debian/dopamine.init b/debian/dopamine.init
--- a/debian/dopamine.init
+++ b/debian/dopamine.init
@@ -1,156 +1,158 @@
 #! /bin/sh
 ### BEGIN INIT INFO
 # Provides:          dopamine
-# Required-Start:    $network $remote_fs $syslog
-# Required-Stop:     $network $remote_fs $syslog
+# Required-Start:    $local_fs $remote_fs $network $syslog
+# Required-Stop:     $local_fs $remote_fs $network $syslog
+# Should-Start:      postgresql
+# Should-Stop:       postgresql
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: A document-oriented PACS
-# Description:       Dopamine is document-oriented PACS
+# Short-Description: Dopamine init script
+# Description:       Dopamine - Document-oriented PACS
 ### END INIT INFO
 
-NAME=dopamine
+# Author: Julien Lamy <lamy@unistra.fr>
+
+# Do NOT "set -e"
+
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+
+# You can modify the variables below
+DESC="Dopamine"
+NAME=Dopamine
+
+# Constants
 DAEMON=/usr/bin/dopamine
-DESC=PACS
-RUNDIR=/var/run/dopamine
-PIDFILE=${RUNDIR}/${NAME}.pid
+DAEMON_ARGS="-f /etc/dopamine.ini"
+PIDFILE=/run/dopamine.pid
+SCRIPTNAME=/etc/init.d/dopamine
+DOPAMINE_USER=dopamine:dopamine
 
-if test ! -x ${DAEMON}; then
-    echo "Could not find ${DAEMON}"
-    exit 0
-fi
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
 
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
 . /lib/lsb/init-functions
 
-STARTTIME=1
-# Time to wait for the server to die, in seconds. If this value is set too low
-# you might not let some servers to die gracefully and 'restart' will not work
-DIETIME=10
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
 
-DAEMONUSER=${DAEMONUSER:-dopamine}
-DAEMON_OPTS=${DAEMON_OPTS:-""}
+    start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $DOPAMINE_USER --background --exec $DAEMON --test > /dev/null \
+	|| return 1
 
-running_pid() {
-# Check if a given process pid's cmdline matches a given name
-    pid=$1
-    name=$2
-    [ -z "$pid" ] && return 1
-    [ ! -d /proc/$pid ] &&  return 1
-    cmd=`cat /proc/$pid/cmdline | tr "\000" "\n"|head -n 1 |cut -d : -f 1`
-    # Is this the expected server
-    [ "$cmd" != "$name" ] &&  return 1
+    start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE --chuid $DOPAMINE_USER --background --exec $DAEMON -- $DAEMON_ARGS \
+	|| return 2
+
+    # Add code here, if necessary, that waits for the process to be ready
+    # to handle requests from services started subsequently which depend
+    # on this one.  As a last resort, sleep for some time.
+}
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+    # Return
+    #   0 if daemon has been stopped
+    #   1 if daemon was already stopped
+    #   2 if daemon could not be stopped
+    #   other if a failure occurred
+    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --chuid $DOPAMINE_USER --name $NAME
+    RETVAL="$?"
+    [ "$RETVAL" = 2 ] && return 2
+
+    # Wait for children to finish too if this is a daemon that forks
+    # and if the daemon is only ever run from this initscript.
+    # If the above conditions are not satisfied then add some other code
+    # that waits for the process to drop all resources that could be
+    # needed by services started subsequently.  A last resort is to
+    # sleep for some time.
+    start-stop-daemon --stop --quiet --oknodo --retry=0/1/KILL/5 --chuid $DOPAMINE_USER --exec $DAEMON
+    [ "$?" = 2 ] && return 2
+    # Many daemons don't delete their pidfiles when they exit.
+    rm -f $PIDFILE
+    return "$RETVAL"
+}
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+    #
+    # If the daemon can reload its configuration without
+    # restarting (for example, when it is sent a SIGHUP),
+    # then implement that here.
+    #
+    start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --chuid $DOPAMINE_USER --name $NAME
     return 0
-}
-
-running() {
-# Check if the process is running looking at /proc
-# (works for all users)
-
-    # No pidfile, probably no daemon present
-    [ ! -f "$PIDFILE" ] && return 1
-    pid=`cat $PIDFILE`
-    running_pid $pid $DAEMON || return 1
-    return 0
-}
-
-start_server() {
-    test -e "${RUNDIR}" || install -m 755 -o dopamine -g dopamine -d "${RUNDIR}"
-    start-stop-daemon --background --start --quiet --pidfile ${PIDFILE} \
-        --make-pidfile --chuid ${DAEMONUSER} --exec ${DAEMON} -- ${DAEMON_OPTS}
-    errcode=$?
-    return ${errcode}
-}
-
-stop_server() {
-    start-stop-daemon --stop --quiet --pidfile ${PIDFILE} \
-        --user ${DAEMONUSER} --exec ${DAEMON}
-    errcode=$?
-    return ${errcode}
 }
 
 case "$1" in
     start)
-        log_daemon_msg "Starting $DESC" "$NAME"
-        # Check if it's running first
-        if running ;  then
-            log_progress_msg "apparently already running"
-            log_end_msg 0
-            exit 0
-        fi
-        if start_server ; then
-            # NOTE: Some servers might die some time after they start,
-            # this code will detect this issue if STARTTIME is set
-            # to a reasonable value
-            [ -n "$STARTTIME" ] && sleep $STARTTIME # Wait some time
-            if  running ;  then
-                # It's ok, the server started and is running
-                log_end_msg 0
-            else
-                # It is not running after we did start
-                log_end_msg 1
-        fi
-        else
-            # Either we could not start it
-            log_end_msg 1
-        fi
-        ;;
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+	    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+	    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
     stop)
-        log_daemon_msg "Stopping $DESC" "$NAME"
-        if running ; then
-            # Only stop the server if we see it running
-            errcode=0
-            stop_server || errcode=$?
-            log_end_msg $errcode
-        else
-            # If it's not running don't do anything
-            log_progress_msg "apparently not running"
-            log_end_msg 0
-            exit 0
-        fi
-        ;;
-    force-stop)
-        # First try to stop gracefully the program
-        $0 stop
-        if running; then
-            # If it's still running try to kill it more forcefully
-            log_daemon_msg "Stopping (force) $DESC" "$NAME"
-            errcode=0
-            force_stop || errcode=$?
-            log_end_msg $errcode
-        fi
-        ;;
-    restart|force-reload)
-        log_daemon_msg "Restarting $DESC" "$NAME"
-        errcode=0
-        stop_server || errcode=$?
-        # Wait some sensible amount, some server need this
-        [ -n "$DIETIME" ] && sleep $DIETIME
-        start_server || errcode=$?
-        [ -n "$STARTTIME" ] && sleep $STARTTIME
-        running || errcode=$?
-        log_end_msg $errcode
-        ;;
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+	    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
     status)
-        log_daemon_msg "Checking status of $DESC" "$NAME"
-        if running ;  then
-            log_progress_msg "running"
-            log_end_msg 0
-        else
-            log_progress_msg "apparently not running"
-            log_end_msg 1
-            exit 1
-        fi
-        ;;
-    # Dopamine can't reload its configuration.
-    reload)
-        log_warning_msg "Reloading $NAME daemon: not implemented, as the daemon"
-        log_warning_msg "cannot re-read the config file (use restart)."
-        ;;
+	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	;;
+    #reload|force-reload)
+    #
+    # If do_reload() is not implemented then leave this commented out
+    # and leave 'force-reload' as an alias for 'restart'.
+    #
+    #log_daemon_msg "Reloading $DESC" "$NAME"
+    #do_reload
+    #log_end_msg $?
+    #;;
+    restart|force-reload)
+	#
+	# If the "reload" option is implemented then remove the
+	# 'force-reload' alias
+	#
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	    0|1)
+		do_start
+		case "$?" in
+		    0) log_end_msg 0 ;;
+		    1) log_end_msg 1 ;; # Old process is still running
+		    *) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	    *)
+	  	# Failed to stop
+		log_end_msg 1
+		;;
+	esac
+	;;
     *)
-        N=/etc/init.d/$NAME
-        echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
-        exit 1
-        ;;
+	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
+	;;
 esac
 
-exit 0
+:
